version: 2

jobs:
  build:
    docker:
      - image: cibuilds/chrome-extension
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: apk add --no-cache yarn zip
      - run:
          name: "Build Extension"
          command: |
            yarn install
            yarn run build
      - run:
          name: "Package Extension"
          command: zip -r hyperlinker.zip dist/
      - store_artifacts:
          path: /root/project/hyperlinker.zip
      - persist_to_workspace:
          root: /root/project
          paths:
            - hyperlinker.zip
  publish:
    docker:
      - image: cibuilds/chrome-extension
    environment:
      - APP_ID: ipbklljhldnlobbmnjaalbebbahamcmk
    steps:
      - attach_workspace:
          at: /root/workspace
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: publish /root/workspace/hyperlinker.zip

workflows:
  version: 2
  develop-build:
    jobs:
      - build:
          filters:
            branches:
              only: develop
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/
