name: chrome-extension-publish

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Git tag and package.json declaration match
        run: |
          version="$(cat package.json | grep version | head -n1 | sed -E 's/^.*"version".*"(.*)".*$/\1/')"
          test "$(git rev-parse "v$version")" = "$(git rev-parse HEAD)"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          npm ci
          npm run build
          zip -r dist.zip dist
      - name: Release
        uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7 # v2
        with:
          extension: ipbklljhldnlobbmnjaalbebbahamcmk
          zip: dist.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
